export const CUSTOMER_CONSTANTS = {
  ADD_CUSTOMER: "ADD_CUSTOMER",
  REMOVE_CUSTOMER: "REMOVE_CUSTOMER",
  FETCH_CUSTOMERS_REQUEST: "FETCH_CUSTOMERS_REQUEST",
  FETCH_CUSTOMERS_SUCCESS: "FETCH_CUSTOMERS_SUCCESS",
  FETCH_CUSTOMERS_FAILURE: "FETCH_CUSTOMERS_FAILURE",
};
